server:
  port: 8090
  session:
    cookie:
      name: oauth2Session

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: acme
      client-secret: acme
spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hc
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379
    password: redis001
#  thymeleaf:
#    cache: false

mybatis:
  config-location: classpath:mybatis-config.xml

token:
  secret: "xxxx888lllll"
